language: node_js
node_js:
- '0.10'
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: V2V9tgKJehh57WIA6n/O1NhhxL2HmERtEVnrG8MoK0Ku3IfPV4Ab0HtCyqGi9NzdeeI4DStSU+/nnrD+TstEWx1B7AVzE1fOWtkgocZao+HsY7lGO/oCNa1Fx9HtcGqY7mHGksiX+eawP2o+I55nSWRxWfpJXOkPnvzhTlJ1m+k=
  on:
    tags: true
    repo: Brightspace/return-points
    all_branches: true
